#!/usr/bin/env perl
use strict;
use warnings;
use experimental qw{switch smartmatch };
use POSIX qw{ceil floor};
use Data::Dumper;
$|++; # stream

print qx{ xclip -o > /tmp/student.pl; chmod 755 /tmp/student.pl; echo 'updated'};
sub NOTE($){ 
  my $wid = 40;
  my $str = @_ && length $_[0] ? sprintf qq{ [ %s ] }, shift : '';
  my $pre = ceil ($wid-length $str)/2;
  my $pst = floor ($wid-length $str)/2;
  printf qq{%s%s%s\n}
       , '-'x$pre
       , $str
       , '-'x$pst
}
sub SYS { 
  my $cmd = pop;
  NOTE( @_ ? shift : '' ) and system $cmd;
}
sub RUN { 
  my $note = @_ ? shift : '';
  SYS($note, join ' ', qw{perl -I/tmp /tmp/student.pl}, @_);
}

for( $ARGV[0] ){
  when (undef){ RUN }
  when (/od/){ 
    my $lines = $ARGV[1] || 5;
    RUN 'without -c' => qw{/software/Perl2/regmatch.png | head -n }, $lines;
    SYS 'reference without -c' => qq{od /software/Perl2/regmatch.png | head -n $lines};
    RUN 'with -c' => qw{-c /software/Perl2/regmatch.png | head -n }, $lines;
    SYS 'reference with -c' => qq{od -c /software/Perl2/regmatch.png | head -n $lines};
  }
  when (/ht/){ 
    RUN $_ => $_ for glob '/software/Perl2/ht*';
  }
  default { RUN 'default', @ARGV }
}
